name: Unit Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
    types: [ opened ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          export CONF_URL=${{ secrets.CONF_URL }}
          export CONF_USER=${{ secrets.CONF_USER }}
          export CONF_PASS=${{ secrets.CONF_PASS }}
          python -m pytest tests
